### ISSUE TITLE
Bloque 3 Dispositivos de red.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/redes7a-Archived#6]
Bloque 3 Dispositivos de red.

**Comment by lopezW** [comment]
Gracias por favor de ponerse sus medallas de honor, los que ya terminaron, poner su :1st_place_medal:   

| SYSADMIN 	| First March Server Friday 	|
|:-------------------------------------:	|---------------------------	|
| ALVARADO SOTO JESUS MANUEL 	|  🤔	|
| ALVAREZ ORTEGA ESTEPHANIA 	|  :1st_place_medal: 	|
| AQUINO VAZQUEZ OMAR 	|  :1st_place_medal:	|
| BARBA ANDRADE JOSUE 	|  :1st_place_medal:	|
| BAUTISTA VARGAS JORGE DAMIAN 	|  🤔	|
| CASTILLO ARAGON WALTER 	|  🤔	|
| CEBALLOS PILLADO KARINA IVETH 	|  	:1st_place_medal: |
| CELAYA CARRANCO FAUSTO JAVIER 	|  :1st_place_medal:   	|
| CRUZ ESPINOZA VIANEY KARELI 	|  🤔	|
| DELGADO VALENCIA JUAN 	|  :1st_place_medal: 	|
| GAMEZ GOMEZ DIANA KARINA 	|  :1st_place_medal: 	|
| GUTIERREZ PATIÑO DYLCIA ESTEFANIA 	|  	🤔|
| GUZMAN GARCIA VICTOR RAFAEL 	|  🤔	|
| HE XUAN YANMING 	| :1st_place_medal:  	|
| HERNANDEZ BOCANEGRA MIGUEL ANGEL 	|🤔  	|
| HIDALGO LOPEZ JUAN CARLOS 	|  🥇 |
| ILHUICATZI CAMPOS KASSANDRA CITLALLI 	|  :1st_place_medal: 	|
| LAGARDA MENDEZ LUIS MARTIN 	| 🤔 	| :1st_place_medal: 
| LOPEZ HERNANDEZ OLIVIA CRISTINA 	|:1st_place_medal:   	|
| LOPEZ PEREZ WILBERT ALEXANDER 	|  🤔	|
| MARTINEZ CORONA ANTONIO 	|   :1st_place_medal:	|
| MARTINEZ REYES JULIO ISMAEL 	|  :1st_place_medal:	|
| MONTOYA HEREDIA VICTOR JEHOVANY 	|  :1st_place_medal:|
| MORALES VAZQUEZ JESUS ALEXANDER 	| 🤔 	|
| MUNIVE SALDAÑA EVANS JOSUE 	|  :1st_place_medal:	|
| NODAL CADENA JOSE ANTONIO 	|  🤔	|
| OLVERA RAMOS ENRIQUE JAVIER 	|  🤔	|
| ORTEGA SOTELO ALFREDO 	|  🤔	|
| RAMIREZ CONTRERAS JAIR 	|  :1st_place_medal: 	|
| RAMIREZ VASQUEZ LUIS FERNANDO 	|  🤔	|
| ROSAL MACHAIN JORGE LUIS 	|:1st_place_medal:     	|
| ROSALES GUTIERREZ TERIUS EMILIO 	|  🤔	|
| ROSALES PINEDA ANGEL 	|  🤔	|
| RUBIO ESCALANTE ANGEL DAVID ALEJANDRO 	|  :1st_place_medal:	|
| SAAVEDRA REGALADO CARLOS ANDRES 	|  :1st_place_medal: 	|
| SALCEDO MORALES JOSE MANUEL 	|  	:1st_place_medal:  |
| SEVILLA OMAÑA VANESSA ITZAYANA 	| :1st_place_medal:  	|
| SIQUEIROS LEON MIGUEL ALEJANDRO 	|  	🤔|
| TORRES MARTINEZ ALEJANDRO 	|  🤔	|
| VERA MALDONADO ERNESTO 	|  	:1st_place_medal:|
| VILLALOBOS ALCARAZ LUIS EDUARDO 	|  	🥇|
| VILLEGAS CASTILLO OMAR 	|  :1st_place_medal:    	|

**Comment by Antonio-Mtz** [comment]
Server Xeon 1 Servicios configurados

|He Xuan Yanming	| CIFS |  :1st_place_medal: 	|
|Lagarda Mendez Luis Martin	| FTP |  :1st_place_medal: 	|
|Hidalgo Lopez Juan Carlos| ISCSI |  :1st_place_medal: 	|
|He Xuan Yanming	| CIFS |  :1st_place_medal: 	|
|Siqueiros Leon Miguel Alejandro| AFP |  :1st_place_medal: 	|

**Comment by Antonio-Mtz** [comment]
|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |

**Comment by lopezW** [comment]
| NOMBRE| SERVICIO | ESTADO |
|---|---|---|
|Wilbert Lopez Perez| ADMIN |  :1st_place_medal: 	|
|   |   |   |
| CEBALLOS PILLADO KARINA IVETH 	|  FTP 	 |   |
| VILLALOBOS ALCARAZ LUIS EDUARDO 	|  FTP |   |
| CELAYA CARRANCO FAUSTO JAVIER 	|ISCI   |   |
| VILLEGAS CASTILLO OMAR 	|   NFS   	|   |
| SAAVEDRA REGALADO CARLOS ANDRES 	|   SMNP	|   |
| MUNIVE SALDAÑA EVANS JOSUE 	|  	ISCI   |   |
| DELGADO VALENCIA JUAN 	|   	SMNP	|   |
| LOPEZ HERNANDEZ OLIVIA CRISTINA 	|  CIFS 	|   |
| RAMIREZ CONTRERAS JAIR 	|  FTP 	|   |
| RAMIREZ VASQUEZ LUIS FERNANDO 	|  SSH	|   |
| OLVERA RAMOS ENRIQUE JAVIER 	|  	AFP|   |
| SALCEDO MORALES JOSE MANUEL 	|  	AirSync  |   |
